# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRm2G7Is8d_Z-0BBR-7zg-2JWFFrRway
"""

!pip install tensorflow keras

#  ANN TRAIN

# 1. Upload & unzip dataset
from google.colab import files
import zipfile, os

uploaded = files.upload()  # chọn file .zip (vd: data_mono.zip)
zip_path = next(iter(uploaded.keys()))

extract_path = "/content/P_mono"
!rm -rf {extract_path}
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# 2. Duyệt dữ liệu ảnh
import cv2
import numpy as np

x_data, y_data = [], []
 # Correctly list the class directories within the nested folder
class_base_path = os.path.join(extract_path, "P_mono")
class_names = sorted([name for name in os.listdir(class_base_path) if os.path.isdir(os.path.join(class_base_path, name))])

print("Classes:", class_names)

for label, class_name in enumerate(class_names):
    class_dir = os.path.join(class_base_path, class_name)
  # Recursively walk through subdirectories to find image files
    for root, dirs, files_in_dir in os.walk(class_dir):
        for fname in files_in_dir:
            fpath = os.path.join(root, fname)
            # Check if the file is an image (basic check based on extension)
            if fname.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.gif')):
                img = cv2.imread(fpath, cv2.IMREAD_GRAYSCALE)
                if img is None:
                    print(f"Warning: Could not read image file: {fpath}")
                    continue
                img_resized = cv2.resize(img, (60, 60))
                x_data.append(img_resized)
                y_data.append(label)

x_data = np.array(x_data, dtype="float32") / 255.0
y_data = np.array(y_data, dtype="int")

print("Dataset shape:", x_data.shape, y_data.shape)

  # 3. Reshape & one-hot
if x_data.shape[0] > 0: # Only proceed if data is loaded
  x_data = x_data.reshape(x_data.shape[0], 60*60)  # flatten
  from keras.utils import to_categorical
  y_data = to_categorical(y_data, num_classes=len(class_names))

  # 4. Chia train/test
  from sklearn.model_selection import train_test_split
  x_train, x_test, y_train, y_test = train_test_split(
      x_data, y_data, test_size=0.2, random_state=42
  )

  print("Train:", x_train.shape, y_train.shape)
  print("Test:", x_test.shape, y_test.shape)

  # 5. Xây dựng ANN
  from keras.models import Sequential
  from keras.layers import Dense
  from keras.layers import Dropout # Import Dropout layer

  model = Sequential()
  model.add(Dense(512, activation='relu', input_shape=(60*60,))) # Changed input shape
  model.add(Dropout(0.3)) # Added Dropout layer
  model.add(Dense(256, activation='relu')) # Added Dense layer
  model.add(Dropout(0.3)) # Added Dropout layer
  model.add(Dense(len(class_names), activation='softmax')) # Output layer with correct number of classes

  model.compile(optimizer="rmsprop",
                loss="categorical_crossentropy",
                metrics=["accuracy"])

  model.summary()

  # 6. Huấn luyện
  history = model.fit(x_train, y_train,
                      epochs=500,
                      batch_size=128,
                      validation_data=(x_test, y_test))

  # 7. Lưu model
  model.save("final_model.h5")
  print("Model saved!")

# UP ẢNH ĐỂ TEST

from google.colab import files
uploaded = files.upload()
fname = next(iter(uploaded.keys()))

import cv2
import numpy as np
import matplotlib.pyplot as plt

IMG_SIZE = 60

# 1. Đọc ảnh màu gốc
img_color = cv2.imread(fname, cv2.IMREAD_COLOR)
if img_color is None:
    raise ValueError("Không đọc được ảnh test!")

# 2. Tạo bản resize grayscale để predict
img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
img_resized = cv2.resize(img_gray, (IMG_SIZE, IMG_SIZE)) # Changed image size
img_norm = img_resized.astype("float32") / 255.0
img_ready = img_norm.reshape(1, IMG_SIZE*IMG_SIZE) # Changed image size

# 3. Dự đoán
preds = model.predict(img_ready)
digit = class_names[np.argmax(preds)]
print("✅ Dự đoán:", digit)

# 4. Hiển thị ảnh
plt.imshow(cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.title(f"Dự đoán: {digit}")
plt.show()

from google.colab import files, output
import cv2, numpy as np, base64
from IPython.display import display, HTML

# ===== Bảng ý nghĩa chỉ tay =====
palmistry_info = {
    "Chỉ tay chữ M": "Người có đường chỉ tay chữ M thường được cho là có tài năng đặc biệt, thông minh, và may mắn. Họ có khả năng lãnh đạo, trực giác tốt và thường đạt được thành công lớn trong sự nghiệp và cuộc sống.",
    "Chỉ tay chữ nhất": "Người có đường chỉ tay chữ Nhất thường có tính cách mạnh mẽ và quyết đoán. Họ có khả năng tập trung cao độ và thường đạt được thành công trong những lĩnh vực đòi hỏi sự kiên trì và quyết tâm. Tuy nhiên, họ cũng có thể gặp khó khăn trong việc cân bằng giữa lý trí và cảm xúc.",
    "Chỉ tay chữ X": "Người có đường chỉ tay chữ X thường được coi là có sức mạnh bảo vệ đặc biệt và may mắn. Họ có khả năng vượt qua khó khăn và thường được bảo vệ khỏi những rủi ro lớn.",
    "Chỉ tay đuôi cá": "Người có đường chỉ tay đuôi cá thường được coi là có may mắn đặc biệt và thường gặp được nhiều cơ hội tốt trong cuộc sống. Họ có khả năng vượt qua khó khăn và đạt được thành công lớn.",
    "Chỉ tay mắt phượng": "Người có đường chỉ tay mắt phượng thường có trực giác tốt, trí tuệ cao và khả năng nhìn xa trông rộng. Họ thường được quý nhân phù trợ và có nhiều cơ hội thành công trong cuộc sống.",
    "Chỉ tay thỏi vàng": "Người có đường chỉ tay thỏi vàng thường được cho là có tài lộc, thịnh vượng và thành công trong sự nghiệp. Họ có khả năng quản lý tài chính tốt và thường gặp may mắn trong kinh doanh.",
}

IMG_SIZE = 28  # cho model

# ===== Hàm dự đoán =====
def run_prediction():
    uploaded = files.upload()
    fname = next(iter(uploaded.keys()))

    # Đọc ảnh màu gốc
    img_color = cv2.imread(fname)
    img_color = cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB)

    # Chuẩn bị grayscale cho model
    img_gray = cv2.cvtColor(img_color, cv2.COLOR_RGB2GRAY)
    img_resized = cv2.resize(img_gray, (IMG_SIZE, IMG_SIZE))
    img_norm = img_resized.astype("float32")/255.0
    img_ready = img_norm.reshape(1, IMG_SIZE*IMG_SIZE)

    # Dự đoán
    preds = model.predict(img_ready)[0]
    top_index = preds.argmax()
    top_label = class_names[top_index]
    top_prob = preds[top_index]

    # Mô tả
    description = palmistry_info.get(top_label, "Thông tin về đường chỉ tay này chưa có trong cơ sở dữ liệu.")

    # Encode ảnh gốc (giữ nguyên màu)
    max_display_w = 400
    h, w = img_color.shape[:2]
    scale = min(max_display_w / w, 1.0)
    new_w, new_h = int(w*scale), int(h*scale)
    img_display = cv2.resize(img_color, (new_w, new_h))

    _, buffer = cv2.imencode('.png', cv2.cvtColor(img_display, cv2.COLOR_RGB2BGR))
    img_base64 = base64.b64encode(buffer).decode('utf-8')

    # HTML kết quả
    html_result = f"""
        <div>
            <img src="data:image/png;base64,{img_base64}"
                 style="max-width:400px; border-radius:15px; box-shadow:0 0 20px #ba68c8;">
            <div style="margin-top:10px; font-size:24px; font-weight:bold; color:#E1BEE7; text-shadow:0 0 10px #ab47bc;">
                🔮 Kết quả: {top_label} ({top_prob*100:.2f}%)
            </div>
            <p style='margin-top:12px; font-size:18px; color:#CE93D8; font-family:Raleway;'>{description}</p>
        </div>
    """

    display(HTML(f"""
        <script>
            document.getElementById('result').innerHTML = `{html_result}`;
            document.getElementById('resetBtn').style.display = 'inline-block';
        </script>
    """))

# ===== Callback =====
def predict_palm(): run_prediction()
def reset_and_predict(): run_prediction()

output.register_callback('predict_palm', predict_palm)
output.register_callback('reset_and_predict', reset_and_predict)

# ===== HTML giao diện huyền bí =====
display(HTML("""
<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<title>🔮 Xem chỉ tay huyền bí 🔮</title>
<link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@700&family=Raleway:wght@400;600&display=swap" rel="stylesheet">
<style>
    body {
        font-family: 'Raleway', sans-serif;
        background: radial-gradient(circle at top, #2e003e, #000000 80%);
        text-align: center;
        padding: 50px;
        color: #fff;
    }
    h1 {
        font-family: 'Cinzel Decorative', cursive;
        color: #E1BEE7;
        font-size: 50px;
        margin-bottom: 30px;
        text-shadow: 0 0 20px #ba68c8, 0 0 40px #7b1fa2;
    }
    .card {
        background: rgba(20, 0, 30, 0.85);
        padding: 35px;
        border-radius: 20px;
        box-shadow: 0px 0px 30px rgba(138,43,226,0.7);
        max-width: 700px;
        margin: auto;
        border: 2px solid #9c27b0;
    }
    button {
        margin-top: 25px;
        padding: 14px 35px;
        font-size: 20px;
        border: none;
        border-radius: 50px;
        cursor: pointer;
        font-weight: bold;
        transition: all 0.3s ease;
        color: #fff;
    }
    #predictBtn {
        background: linear-gradient(45deg, #7b1fa2, #ab47bc);
        box-shadow: 0px 0px 20px rgba(171,71,188,0.9);
    }
    #predictBtn:hover {
        transform: scale(1.05);
        box-shadow: 0px 0px 30px rgba(186,104,200,1);
    }
    #resetBtn {
        background: linear-gradient(45deg, #4527a0, #5e35b1);
        display: none;
    }
    #result {
        margin-top: 30px;
        font-size: 26px;
        font-weight: bold;
        color: #CE93D8;
        text-shadow: 0 0 10px #f3e5f5;
    }
</style>
</head>
<body>
    <h1>🔮 Xem chỉ tay – Giải mã vận mệnh 🔮</h1>
    <div class="card">
        <button id="predictBtn" onclick="google.colab.kernel.invokeFunction('predict_palm', [], {});">
            ✋ Tải ảnh bàn tay & Xem chỉ tay
        </button>
        <button id="resetBtn" onclick="google.colab.kernel.invokeFunction('reset_and_predict', [], {});">
            🔄 Xem bàn tay khác
        </button>
        <div id="result"></div>
    </div>
</body>
</html>
"""))